allowBuilds:
    canvas: true
    esbuild: false
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
    - '@eejit/eslint-config-typescript'
    - '@eejit/prettier-config'
    - '@eejit/stylelint-config'
publicHoistPattern:
    - '*eslint*'
    - '*prettier*'
